### ISSUE TITLE
paragraphs issue

### ISSUE THREAD

**Issue by jaan143** [evmer/perlego-downloader#5]
please check whole book have this text issue

![Screenshot 2022-09-06 213612](https://user-images.githubusercontent.com/15013833/188689431-2ac3699e-0862-41a5-8e22-7e3469862bb5.jpg)
![Screenshot 2022-09-06 213540](https://user-images.githubusercontent.com/15013833/188689451-1707ddfc-c00f-4fc0-b8d6-ad96032efeda.jpg)

this is book link
https://www.perlego.com/book/3294395/second-language-pronunciation-bridging-the-gap-between-research-and-teaching-pdf

**Comment by evmer** [comment]
Thanks for reporting this to me. After some research I found that this is related to a pdfkit/wkhtmltopdf bug that seems to have been ongoing for 4+ years:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3256
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/45

Unfortunately there's no solution yet, so all I can do is refactor the script replacing pdfkit with another html2pdf library. It's going to take some time, maybe in the next few days I'll come up with something working.

**Comment by jaan143** [comment]
@evmer  well you can check this topic mostly peoples fixed in dpi setting and some not
https://stackoverflow.com/questions/34241932/letter-spacing-is-too-large-with-wkhtmltopdf

**Comment by evmer** [comment]
@jaan143 I refactored the script replacing pdfkit with pyppeteer. Now this bug should be fixed, you can try yourself.

Don't forget to update the python requirements:

> python3 -m pip install pyppeteer

**Comment by jaan143** [comment]
@evmer  thanks for your efforts Dear :)
here is error while converting to pdf in new script

page 347 downloaded
Traceback (most recent call last):
  File "downloader.py", line 183, in <module>
    asyncio.get_event_loop().run_until_complete(html2pdf())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "downloader.py", line 114, in html2pdf
    browser = await launch(options={
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

PS C:\Users\Hp\Downloads\Compressed\perlego-downloader-main\perlego-downloader-main_4 (new pdf convert library)\perlego-downloader-main>

**Comment by evmer** [comment]
@jaan143 seems your system is missing some required dependencies:

https://stackoverflow.com/questions/57217924/pyppeteer-errors-browsererror-browser-closed-unexpectedly

**Comment by jaan143** [comment]
@evmer  check this
downloader.py:183: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(html2pdf())

i read a lot topics and they fixing issue in their project code 
i think you need to add timeout session 
but i dont know exactly

**Comment by evmer** [comment]
@jaan143 can you please describe better your issue?

This is just a warning and shouldn't break the script execution:

`downloader.py:183: DeprecationWarning: There is no current event loop
asyncio.get_event_loop().run_until_complete(html2pdf())`

**Comment by jaan143** [comment]
@evmer  actually issue is the same which i show above 
and i spend whole day to get help from internet (github stackoverflow etc)
but cannot get proper answer mostly there are linux related helps

Traceback (most recent call last):
File "downloader.py", line 183, in
asyncio.get_event_loop().run_until_complete(html2pdf())
File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
return future.result()
File "downloader.py", line 114, in html2pdf
browser = await launch(options={
File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
return await Launcher(options, **kwargs).launch()
File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
self.browserWSEndpoint = get_ws_endpoint(self.url)
File "C:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

PS C:\Users\Hp\Downloads\Compressed\perlego-downloader-main\perlego-downloader-main_4 (new pdf convert library)\perlego-downloader-main>

**Comment by evmer** [comment]
@jaan143 I updated the script, can you please try now?

**Comment by jaan143** [comment]
@evmer  ok let me confirm you

**Comment by jaan143** [comment]
@evmer  still the same. what OS you are using ?
C:\Users\Hp\Downloads\Compressed\perlego-downloader-main\perlego-downloader-main 5\perlego-downloader-main\downloader.py:184: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(html2pdf())
Traceback (most recent call last):
  File "C:\Users\Hp\Downloads\Compressed\perlego-downloader-main\perlego-downloader-main 5\perlego-downloader-main\downloader.py", line 184, in <module>
    asyncio.get_event_loop().run_until_complete(html2pdf())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Hp\Downloads\Compressed\perlego-downloader-main\perlego-downloader-main 5\perlego-downloader-main\downloader.py", line 114, in html2pdf
    browser = await launch(options={
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

PS C:\Users\Hp\Downloads\Compressed\perlego-downloader-main\perlego-downloader-main 5\perlego-downloader-main>

**Comment by evmer** [comment]
@jaan143 I tested it on MacOSX, Linux (Debian) and Windows 10, so it seems a problem related to your configuration. 

Can you please follow [these instructions](https://github.com/pyppeteer/pyppeteer/issues/108#issuecomment-642034439) for troubleshoot and post the output here?

**Comment by jaan143** [comment]
@evmer  he saying copy command and run in powershell or cmd but he is asking for docker or aws.
anyway i just copied and past in my powershell and here screenshot you can see
![Screenshot 2022-09-08 161259](https://user-images.githubusercontent.com/15013833/189186931-c639a225-9226-4d2d-8799-78cecb6ed994.jpg)

**Comment by evmer** [comment]
@jaan143 can you please copy-paste the print command and run it? I mean this:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/10036897/189187591-bf58c910-97d2-41f3-b70f-5a420cdaaef6.png">

**Comment by jaan143** [comment]
@evmer  here is
![Screenshot 2022-09-08 223526](https://user-images.githubusercontent.com/15013833/189189031-dad3e15f-94f7-4dac-836e-0111aaf64947.jpg)

**Comment by evmer** [comment]
@jaan143 to run an executable on powershell you first have to 'dot' source the script, so for you:

`./root/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome...etc.`

**Comment by jaan143** [comment]
@evmer here is with dot
![Screenshot 2022-09-08 224425](https://user-images.githubusercontent.com/15013833/189190592-5df9ff42-0cb2-4d33-a6e3-929d4b12b4cd.jpg)

**Comment by evmer** [comment]
@jaan143 I'm not familiar with powershell, try to google the error and make it work

**Comment by jaan143** [comment]
@evmer  here is cmd
![Screenshot 2022-09-08 224751](https://user-images.githubusercontent.com/15013833/189191194-f8ccae8b-97fb-4372-91cd-23c431727a5e.jpg)

**Comment by lilfmdude** [comment]
![unknown](https://user-images.githubusercontent.com/34497266/189254622-a696180e-2f63-43d8-8a0c-5c2fb0884aa5.png)

this is what i get any idea i got it this far

**Comment by smack893** [comment]
did you have a plan to update

**Comment by lilfmdude** [comment]
i don't know if im getting closer i am getting this now  
![image](https://user-images.githubusercontent.com/34497266/189566204-25bfff4a-dc8f-433e-b5eb-47ba2e283efc.png)

**Comment by lilfmdude** [comment]
this one is new too hopefully I'm not annoying you with all this
![image](https://user-images.githubusercontent.com/34497266/189567304-88acb769-96e5-4003-9f45-b27865768c0e.png)

**Comment by jaan143** [comment]
@evmer  i dont want to delete html files so can you tell me which lines i need to remove from script code 
then html files will not be delete ?

**Comment by evmer** [comment]
Guys, this is not a chat group, please try to follow the Github's guidelines. The original problem was solved by replacing pdfkit with pyppeteer so now I'll mark this as closed. Feel free to open a new request providing detailed info about your issue. 

@lilfmdude please see my reply to #7. 
@jaan143 i can't address issues regarding puppeeter/pyppeteer. Your OS configuration may be different, try to google the error messages or ping their Github repo.

**Comment by evmer** [comment]
@jaan143 I added some troubleshooting guidelines in the [readme](https://github.com/evmer/perlego-downloader/blob/main/README.md#troubleshoot), let me know if you can solve your issue. Please consider to download the latest version of the script, I fixed some few bugs.

**Comment by jaan143** [comment]
@evmer  its done now 
Thank you very very much :)

**Comment by evmer** [comment]
> @evmer its done now
> Thank you very very much :)

Finally! 😅 So was the missing chromedriver the issue?

**Comment by jaan143** [comment]
@evmer not it was already set in path
problem was in pyppeteer which i reinstall and then pyppeteer reinstall chromium
but if i download epub book format its top and bottom margins of pages are very close with text and also page width and height is very big 
and if download pdf format it is good

**Comment by evmer** [comment]
> but if i download epub book format its top and bottom margins of pages are very close with text and also page width and height is very big

You can try to adjust the margins (in pixels) at line 209: https://github.com/evmer/perlego-downloader/blob/main/downloader.py#L209

**Comment by evmer** [comment]
> problem was in pyppeteer which i reinstall and then pyppeteer reinstall chromium

Can you please elaborate the solution step-by-step? It's a very common issue and you'd make many users happy. Thank you!

**Comment by jaan143** [comment]
@evmer  can i also set page size like A4 or letter ?

**Comment by jaan143** [comment]
@evmer  see this
![Screenshot 2022-09-13 191525](https://user-images.githubusercontent.com/15013833/189925156-dc92c68e-1ddc-4310-afd0-6709eb83eadd.jpg)
after pdf i open and i saw some images are breaks in two pages
here is book url you can check
https://www.perlego.com/book/3260547/cell-biology-a-short-course-pdf
